meta_title: "mnémosyne – Plateforme de partage de mémoires d’étudiants"
meta_description: "Plateforme de partage de mémoires d’étudiants en école supérieure Culture"
meta_image: "mnemosyne.png"
twitter_account: "@mnemosyne_io"
