meta_title: "mnémosyne – Plateforme de partage de mémoires d’étudiants"
meta_description: "Plateforme de partage de mémoires d’étudiants en école supérieure Culture"
meta_image: "image.jpg" # Une image dans votre dossier app/assets/images/
twitter_account: "@mnemosyne_io"
